// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYk4hprF_ArRlHmcrb5SeIcorLgwCXkS4',
    appId: '1:729837592914:web:56d25c0bfaff83b1c69a8b',
    messagingSenderId: '729837592914',
    projectId: 'homework4-97004',
    authDomain: 'homework4-97004.firebaseapp.com',
    storageBucket: 'homework4-97004.firebasestorage.app',
    measurementId: 'G-JF8KNS16F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-yqjcwCv8pmFBSqF5avN-0jZ3t5KMEVc',
    appId: '1:729837592914:android:2cb43c8e20da3ee6c69a8b',
    messagingSenderId: '729837592914',
    projectId: 'homework4-97004',
    storageBucket: 'homework4-97004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL2ZEiFLT7Ato5FgN4W7DGV0K4li9uSQI',
    appId: '1:729837592914:ios:44b9ef580d7ade85c69a8b',
    messagingSenderId: '729837592914',
    projectId: 'homework4-97004',
    storageBucket: 'homework4-97004.firebasestorage.app',
    iosBundleId: 'com.example.msgapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL2ZEiFLT7Ato5FgN4W7DGV0K4li9uSQI',
    appId: '1:729837592914:ios:44b9ef580d7ade85c69a8b',
    messagingSenderId: '729837592914',
    projectId: 'homework4-97004',
    storageBucket: 'homework4-97004.firebasestorage.app',
    iosBundleId: 'com.example.msgapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYk4hprF_ArRlHmcrb5SeIcorLgwCXkS4',
    appId: '1:729837592914:web:8edbbb56d50acc2ac69a8b',
    messagingSenderId: '729837592914',
    projectId: 'homework4-97004',
    authDomain: 'homework4-97004.firebaseapp.com',
    storageBucket: 'homework4-97004.firebasestorage.app',
    measurementId: 'G-B6YJNM5KFV',
  );
}
